blueprint:
  name: 1 Person Multi-Zone Change - App Notification
  description: Send a notification to a device when a person enters a different zone.
  domain: automation
  input:
    person_entity:
      name: Person
      description: Person/Device that will be tracked.
      selector:
        entity:
          domain: person
    notify_device_1:
      name: Mobile Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications.
      default: ''
      selector:
        device:
          integration: mobile_app
    notification_title:
      name: Notification title (Optional)
      description: 'The title of the notification.  Default: Update from {{ person_name
        }}:'
      default: 'Update from {{ person_name }}:'
    notification_message:
      name: Notification message (Optional)
      description: 'The message of the notification.  Default: Moved from {{ trigger.from_state.state
        }} to {{ trigger.to_state.state }}'
      default: Moved from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }}
  source_url: https://community.home-assistant.io/t/track-multiple-people-zones-228-automations-reduced-to-3/266178
trigger:
  platform: state
  entity_id: !input 'person_entity'
variables:
  person_entity: !input 'person_entity'
  person_name: '{{ states[person_entity].name }}'
  notification_title: !input 'notification_title'
  notification_message: !input 'notification_message'
condition:
  condition: template
  value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
action:
- type: notify
  domain: mobile_app
  device_id: !input 'notify_device_1'
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
