---
substitutions:
  device: esp32-ble2
  name: ESP32 BLE Back
  reboot_timeout: 1h
  update_interval: 10min
  plant1: "Garage Garden"
  plant1mac: "C4:7C:8D:6C:2D:BD"
  plant2: "Earthboxes"
  plant2mac: "C4:7C:8D:6C:2D:E4"
  plant3: "Fence Garden"
  plant3mac: "C4:7C:8D:6C:29:39"
  plant4: "AC Units"
  plant4mac: "C4:7C:8D:6C:2A:44"
  plant5: "Driveway"
  plant5mac: "C4:7C:8D:6C:2C:7E"

esphome:
  name: ${device}
  platform: ESP32
  board: esp-wrover-kit

# Common is: wifi, api, ota, web_server, text_sensors (version, wifi-info)
# Logger is: INFO
# Binary sensors are: status
# Sensors are wifi-signal, uptime
# Switches are: restart
<<: !include common/common.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensors.yaml
<<: !include common/sensors.yaml
<<: !include common/switches.yaml

esp32_ble_tracker:

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: ${plant1mac}
    temperature:
      name: ${plant1} Temperature
    moisture:
      name: ${plant1} Moisture
    illuminance:
      name: ${plant1} Illuminance
    conductivity:
      name: ${plant1} Soil Conductivity
    battery_level:
      name: ${plant1} Battery Level

  - platform: xiaomi_hhccjcy01
    mac_address: ${plant2mac}
    temperature:
      name: ${plant2} Temperature
    moisture:
      name: ${plant2} Moisture
    illuminance:
      name: ${plant2} Illuminance
    conductivity:
      name: ${plant2} Soil Conductivity
    battery_level:
      name: ${plant2} Battery Level

  - platform: xiaomi_hhccjcy01
    mac_address: ${plant3mac}
    temperature:
      name: ${plant3} Temperature
    moisture:
      name: ${plant3} Moisture
    illuminance:
      name: ${plant3} Illuminance
    conductivity:
      name: ${plant3} Soil Conductivity
    battery_level:
      name: ${plant3} Battery Level

  - platform: xiaomi_hhccjcy01
    mac_address: ${plant4mac}
    temperature:
      name: ${plant4} Temperature
    moisture:
      name: ${plant4} Moisture
    illuminance:
      name: ${plant4} Illuminance
    conductivity:
      name: ${plant4} Soil Conductivity
    battery_level:
      name: ${plant4} Battery Level

  - platform: xiaomi_hhccjcy01
    mac_address: ${plant5mac}
    temperature:
      name: ${plant5} Temperature
    moisture:
      name: ${plant5} Moisture
    illuminance:
      name: ${plant5} Illuminance
    conductivity:
      name: ${plant5} Soil Conductivity
    battery_level:
      name: ${plant5} Battery Level
